version: "2"
services:
  auth:
    container_name: auth
    restart: always
    build: .
    ports:
      - "3003:3003"
    links:
      - db
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"